parameters:
    # name of the monorepo package, for UPGRADE.md and CHANGELOG.md links
    monorepo_package_name: "shopsys/shopsys"

services:
    _defaults:
        autowire: true

    Shopsys\Releaser\:
        resource: "../src"
        exclude: "../src/Exception"

    GuzzleHttp\Client: ~
