parameters:
    # name of the monorepo package, for UPGRADE.md and CHANGELOG.md links
    monorepo_package_name: "shopsys/shopsys"

    # @todo this might not be needed
    # list of packages to allow in specific "require" version (without ^ in like "^5.6")
    lock_version_allowed_packages: []

services:
    _defaults:
        autowire: true

    Shopsys\Releaser\:
        resource: "../src"
        exclude: "../src/Exception"

    GuzzleHttp\Client: ~
